/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tuan2;

import java.awt.Component;
import static javafx.scene.input.KeyCode.J;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author hv
 */
public class frmCheckBoxRadioButton extends javax.swing.JFrame {

    /**
     * Creates new form frmCheckBoxRadioButton
     */
    public frmCheckBoxRadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupColor = new javax.swing.ButtonGroup();
        jpnCacSoThich = new javax.swing.JPanel();
        cbDocSach = new javax.swing.JCheckBox();
        cbXemPhim = new javax.swing.JCheckBox();
        c = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jpnMauThichNhat = new javax.swing.JPanel();
        rdXanh = new javax.swing.JRadioButton();
        rdDo = new javax.swing.JRadioButton();
        rdDen = new javax.swing.JRadioButton();
        rdHong = new javax.swing.JRadioButton();
        rdTim = new javax.swing.JRadioButton();
        rdTrang = new javax.swing.JRadioButton();
        btnKetQuaChon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CheckBox và RadioButton");

        jpnCacSoThich.setBorder(javax.swing.BorderFactory.createTitledBorder("Các sở thích"));

        cbDocSach.setText("Đọc sách");

        cbXemPhim.setText("Xem phim");

        c.setText("Nghe nhạc");

        jCheckBox4.setText("Du lịch");

        jCheckBox5.setText("Ăn uống");

        jCheckBox6.setText("Thể thao");

        javax.swing.GroupLayout jpnCacSoThichLayout = new javax.swing.GroupLayout(jpnCacSoThich);
        jpnCacSoThich.setLayout(jpnCacSoThichLayout);
        jpnCacSoThichLayout.setHorizontalGroup(
            jpnCacSoThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCacSoThichLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnCacSoThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c)
                    .addComponent(cbXemPhim)
                    .addComponent(cbDocSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jpnCacSoThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jpnCacSoThichLayout.setVerticalGroup(
            jpnCacSoThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCacSoThichLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpnCacSoThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDocSach)
                    .addComponent(jCheckBox4))
                .addGap(18, 18, 18)
                .addGroup(jpnCacSoThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbXemPhim)
                    .addComponent(jCheckBox5))
                .addGap(18, 18, 18)
                .addGroup(jpnCacSoThichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c)
                    .addComponent(jCheckBox6))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jpnMauThichNhat.setBorder(javax.swing.BorderFactory.createTitledBorder("Màu thích nhất"));

        btnGroupColor.add(rdXanh);
        rdXanh.setText("Màu xanh");

        btnGroupColor.add(rdDo);
        rdDo.setText("Màu đỏ");

        btnGroupColor.add(rdDen);
        rdDen.setText("Màu đen");

        btnGroupColor.add(rdHong);
        rdHong.setText("Màu hồng");

        btnGroupColor.add(rdTim);
        rdTim.setText("Màu tím");

        btnGroupColor.add(rdTrang);
        rdTrang.setText("Màu trắng");

        javax.swing.GroupLayout jpnMauThichNhatLayout = new javax.swing.GroupLayout(jpnMauThichNhat);
        jpnMauThichNhat.setLayout(jpnMauThichNhatLayout);
        jpnMauThichNhatLayout.setHorizontalGroup(
            jpnMauThichNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMauThichNhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMauThichNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdXanh)
                    .addComponent(rdDo)
                    .addComponent(rdDen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnMauThichNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdHong)
                    .addComponent(rdTim)
                    .addComponent(rdTrang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnMauThichNhatLayout.setVerticalGroup(
            jpnMauThichNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMauThichNhatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpnMauThichNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdXanh)
                    .addComponent(rdHong))
                .addGap(18, 18, 18)
                .addGroup(jpnMauThichNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdDo)
                    .addComponent(rdTim))
                .addGap(18, 18, 18)
                .addGroup(jpnMauThichNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdDen)
                    .addComponent(rdTrang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnKetQuaChon.setText("Kết quả chọn");
        btnKetQuaChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetQuaChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnCacSoThich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jpnMauThichNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnKetQuaChon)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnMauThichNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnCacSoThich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnKetQuaChon)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKetQuaChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetQuaChonActionPerformed
        // TODO add your handling code here:
        String hobbies = "",color = "";
        for(Component cpn:jpnCacSoThich.getComponents()){
            JCheckBox jcb = (JCheckBox) cpn;
            if(jcb.isSelected())
            {
                hobbies+=jcb.getText() +", ";
            }
        }
        hobbies = hobbies.substring(0,hobbies.length()-1);
        //hobbies = hobbies;
        for(Component cpn1:jpnMauThichNhat.getComponents()){
            JRadioButton jrb = (JRadioButton) cpn1;
            if(jrb.isSelected()){
                color+=jrb.getText();
                break;
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Hobbies: "+ hobbies + "\nFav Color: " + color);
    }//GEN-LAST:event_btnKetQuaChonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCheckBoxRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCheckBoxRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCheckBoxRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCheckBoxRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCheckBoxRadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupColor;
    private javax.swing.JButton btnKetQuaChon;
    private javax.swing.JCheckBox c;
    private javax.swing.JCheckBox cbDocSach;
    private javax.swing.JCheckBox cbXemPhim;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JPanel jpnCacSoThich;
    private javax.swing.JPanel jpnMauThichNhat;
    private javax.swing.JRadioButton rdDen;
    private javax.swing.JRadioButton rdDo;
    private javax.swing.JRadioButton rdHong;
    private javax.swing.JRadioButton rdTim;
    private javax.swing.JRadioButton rdTrang;
    private javax.swing.JRadioButton rdXanh;
    // End of variables declaration//GEN-END:variables
}
