/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tuan4;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author BaoHa
 */
public class BT5_3_MangHaiChieu extends javax.swing.JFrame {

    /**
     * Creates new form BT5_3_MangHaiChieu
     */
    public BT5_3_MangHaiChieu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRow = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCol = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArray = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnProcess = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dòng:");

        jLabel2.setText("Cột:");

        txtArray.setColumns(20);
        txtArray.setLineWrap(true);
        txtArray.setRows(5);
        txtArray.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtArray);

        jLabel3.setText("Mảng phát sinh:");

        txtResult.setEditable(false);
        txtResult.setColumns(20);
        txtResult.setLineWrap(true);
        txtResult.setRows(5);
        txtResult.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtResult);

        jLabel4.setText("KQ:");

        btnProcess.setText("Xử lý");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRow, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(txtCol))
                        .addGap(18, 18, 18)
                        .addComponent(btnProcess))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcess))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int findMax(int[][] arr,int row,int col){
        int max=0;
        for(int i =0;i<row;i++){
            for(int j=0;j<col;j++){
                if(max<arr[i][j]){
                    max = arr[i][j];
                }
            }
        }
        return max;
    }
    
    private int findMin(int[][] arr,int row,int col){
        int min=0;
        for(int i =0;i<row;i++){
            for(int j=0;j<col;j++){
                if(min>arr[i][j]){
                    min = arr[i][j];
                }
            }
        }
        return min;
    }
    
    
    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int row=0,col=0;
        try{
            row = Integer.parseInt(txtRow.getText());
            col = Integer.parseInt(txtCol.getText());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Bug: "+ex.getMessage());
        }
        
        //TODO: Declare Variable 
        int[][] arr = new int[row][col];
        int countChan=0,countLe=0,max=0,min=0,max2=0,min2=0;
        float tbChan=0,tbLe=0;
        String arrString="",result="";
        Random r = new Random();
        
        //TODO: Process following requirement
        for(int i=0;i<row;i++){
            for(int j=0;j<col;j++){
                arr[i][j] = r.nextInt(100);
                arrString += arr[i][j] + " ";
                if(arr[i][j]%2==0){
                    tbChan+=arr[i][j];
                    countChan++;
                }
                if(arr[i][j]%2!=0){
                    tbLe+=arr[i][j];
                    countLe++;
                }
            }
            
            arrString += "\n";
        }
        tbChan = tbChan/countChan;
        tbLe = tbLe/countLe;
        result += "Số phần tử chẵn: "+ countChan + "\n";
        result += "Số phần tử lẻ: "+ countLe + "\n";
        result += "TB Chẵn:" + tbChan + "\n";
        result += "TB lẻ:" + tbLe + "\n";
        result += "GT Max: "+ findMax(arr, row, col) + "\n";
        result += "GT Min: "+ findMin(arr, row, col) + "\n";
        txtArray.setText(arrString);
        txtResult.setText(result);
    }//GEN-LAST:event_btnProcessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BT5_3_MangHaiChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BT5_3_MangHaiChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BT5_3_MangHaiChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BT5_3_MangHaiChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BT5_3_MangHaiChieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArray;
    private javax.swing.JTextField txtCol;
    private javax.swing.JTextArea txtResult;
    private javax.swing.JTextField txtRow;
    // End of variables declaration//GEN-END:variables
}
