/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tuan4;

import Tuan2.*;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vu Thanh Dat
 */
public class BT6_4 extends javax.swing.JFrame {

    /**
     * Creates new form frmBT3_2
     */
    List<LienHe> listLienHe;
    DefaultTableModel dtm = null;
    
    public BT6_4() {
        initComponents();
        listLienHe = new ArrayList<>();
    }

    private List<LienHe> readFile(){
        List<LienHe> listLH = new ArrayList<>();
        //LienHe[] lh={};
        try {
            ObjectInputStream ois = new ObjectInputStream(new BufferedInputStream(new FileInputStream("lh.obj")));
            while(true){
                try{
                     listLH.add((LienHe)ois.readObject());
                }catch (EOFException ex1){
                    break;
                    //System.out.println(ex1.getMessage());
                }
            }
            //lh = (LienHe[])ois.readObject();
            ois.close();
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(BT6_4.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(BT6_4.class.getName()).log(Level.SEVERE, null, ex);
        }
        return listLH;
    }
    
    private LienHe[] readFilebyArray(){
        try {
            ObjectInputStream ois = new ObjectInputStream(new BufferedInputStream(new FileInputStream("lh.obj")));
            LienHe[] listLH = (LienHe[])ois.readObject();
            return listLH;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BT6_4.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BT6_4.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BT6_4.class.getName()).log(Level.SEVERE, null, ex);
        }
        LienHe[] listLH = new LienHe[0];
        return null;
    }
    
    private void writeFile(String name,String phone,String fileUrl){
        try{
            LienHe[] lh= new LienHe[]{new LienHe(name, phone, fileUrl)};
            ObjectOutputStream oos = new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream("lh.obj",true))){
                @Override
                protected void writeStreamHeader() throws IOException{
                    reset();
                }
            };
            oos.writeObject(lh);
            oos.flush();
            oos.close();
        } catch (IOException ex) {
            Logger.getLogger(BT6_4.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(BT6_4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTapTinHinh = new javax.swing.JTextField();
        btnThemLienHe = new javax.swing.JButton();
        lblHinhAnh = new javax.swing.JLabel();
        btnChonHinh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnXoaLienHe = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnDocDSLienHe = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin liên hệ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Họ tên");

        jLabel2.setText("Điện thoại");

        jLabel3.setText("Hình ảnh");

        btnThemLienHe.setText("Thêm liên hệ");
        btnThemLienHe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLienHeActionPerformed(evt);
            }
        });

        lblHinhAnh.setText("Hình ảnh");

        btnChonHinh.setText("...");
        btnChonHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonHinhActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên", "Điện thoại", "Hình ảnh"
            }
        ));
        jTable1.setRowHeight(80);
        jScrollPane1.setViewportView(jTable1);

        btnXoaLienHe.setText("Xóa liên hệ");
        btnXoaLienHe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLienHeActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnDocDSLienHe.setText("Đọc danh sách liên hệ");
        btnDocDSLienHe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocDSLienHeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHoTen)
                                    .addComponent(txtDienThoai)
                                    .addComponent(txtTapTinHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemLienHe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoaLienHe)
                                .addGap(18, 18, 18)
                                .addComponent(btnDocDSLienHe))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTim)))
                        .addGap(18, 18, 18)
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTapTinHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChonHinh))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemLienHe)
                            .addComponent(btnXoaLienHe)
                            .addComponent(btnDocDSLienHe)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonHinhActionPerformed
        JFileChooser fc = new JFileChooser("./src/img/");
        fc.setDialogTitle("Chọn một hình ảnh");
        FileNameExtensionFilter ff1 = new FileNameExtensionFilter("Các tập tin *.jpg","jpg");
        FileNameExtensionFilter ff2 = new FileNameExtensionFilter("Các tập tin *.png","png");
        FileNameExtensionFilter ff3 = new FileNameExtensionFilter("Các tập tin *.gif","gif");
        fc.setFileFilter(ff2);
        fc.setFileFilter(ff3);
        fc.setFileFilter(ff1);
        int chon = fc.showOpenDialog(null);
        if(chon==JFileChooser.APPROVE_OPTION){
            File f = fc.getSelectedFile();
            txtTapTinHinh.setText(f.getAbsolutePath());
            ImageIcon icon = new ImageIcon(f.getAbsolutePath());
            icon.setImage(icon.getImage().getScaledInstance(lblHinhAnh.getWidth(), lblHinhAnh.getHeight(),Image.SCALE_DEFAULT));
            lblHinhAnh.setIcon(icon);
        }
    }//GEN-LAST:event_btnChonHinhActionPerformed
    
    private void btnThemLienHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLienHeActionPerformed
        String hoTen, dienThoai, hinhAnh;
        hoTen = txtHoTen.getText();
        dienThoai=txtDienThoai.getText();
        hinhAnh = txtTapTinHinh.getText();
        LienHe lh = new LienHe(hoTen, dienThoai, hinhAnh);
        dtm.addRow(new String[]{hoTen,dienThoai,hinhAnh});
        writeFile(hoTen,dienThoai,hinhAnh);
        JOptionPane.showMessageDialog(rootPane, "Đã thêm liên hệ:"+lh.hoTen+" "+lh.soDT);
    }//GEN-LAST:event_btnThemLienHeActionPerformed

    private void btnXoaLienHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLienHeActionPerformed
        int dongXoa = jTable1.getSelectedRow();
        if(dongXoa>-1)
            dtm.removeRow(dongXoa);
    }//GEN-LAST:event_btnXoaLienHeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dtm = (DefaultTableModel) jTable1.getModel();
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new ImageTableCellRenderer(80, 80));
    }//GEN-LAST:event_formWindowOpened

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnDocDSLienHeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocDSLienHeActionPerformed
        // TODO add your handling code here:
        //LienHe[] listLH = readFile();
        LienHe[] listLH = readFilebyArray();
        //dtm = new DefaultTableModel();
        for(LienHe item:listLH){
            dtm.addRow(new String[]{item.hoTen,item.soDT,item.fileUrl});
        }
        jTable1.setModel(dtm);
    }//GEN-LAST:event_btnDocDSLienHeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BT6_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BT6_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BT6_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BT6_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BT6_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonHinh;
    private javax.swing.JButton btnDocDSLienHe;
    private javax.swing.JButton btnThemLienHe;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaLienHe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtTapTinHinh;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
